sudo: false
language: rust
rust:
  - 1.16.0
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cd svg2polylines
  - cargo build
  - cargo test
  - cd ../svg2polylines-ffi
  - cargo build
  - cargo test
