sudo: false
language: rust
rust:
  - 1.15.0
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cd svg2polylines
  - cargo build
  - cargo test
  - cd ../svg2polylines-ffi
  - cargo build
  - cargo test
