sudo: false
language: rust
rust:
  - 1.31.1
  - stable
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cd svg2polylines
  - cargo build
  - cargo test
  - cargo test --features serde
  - cd ../svg2polylines-ffi
  - cargo build
  - cargo test
