version: 2
jobs:
  test:
    docker:
      - image: rust:1.58.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-cache-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-{{ arch }}
      - run:
          name: Show versions
          command: rustc --version && cargo --version
      - run:
          name: Build
          command: cd svg2polylines && cargo build
      - run:
          name: Run tests (regular)
          command: cd svg2polylines && cargo test
      - run:
          name: Run tests (with serde)
          command: cd svg2polylines && cargo test --features serde
      - save_cache:
          key: v2-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - svg2polylines/target
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-{{ arch }}
          paths:
            - svg2polylines/target
            - /usr/local/cargo
  lint:
    docker:
      - image: rust:1.58.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-lint-cache
      - run: rustup component add clippy
      - run: cd svg2polylines && cargo clippy --all-targets --all-features
      - save_cache:
          key: v2-cargo-lint-cache
          paths:
            - /usr/local/cargo
  rustfmt:
    docker:
      - image: rust:1.58.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-fmt-cache
      - run: rustup component add rustfmt
      - run: cd svg2polylines && cargo fmt -- --check
      - save_cache:
          key: v2-cargo-fmt-cache
          paths:
            - /usr/local/cargo
workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - lint
      - rustfmt

  # Build main every week on Monday at 03:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
      - lint
      - rustfmt
